#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the ls01c usb connection as /dev/ls01c."
echo ""

sudo cp `rospack find ls01c_ftdi`/57-ls01c-laptop.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

